### ISSUE TITLE
dealing with withdrawals

### ISSUE THREAD

**Issue by gureckis** [NYUCCL/counterbalancing#1]
we might want to consider adding a method to the Experiment class called `Experiment.completed(subjectID)` which notifies that a particular person has completed the task.  If the person hasn't completed after a configurable amount of time, the counts for those condition should be adjusted so as to ensure people keep coming in evenly.  if later the person does complete the task then the system should deal with that too.

this is important for online experiments

**Comment by jodeleeuw** [comment]
I realize this issue is closed, but I was working on an experiment where I want to deal with withdrawls intelligently and an idea came to mind. 

Doesn't PsiTurk know if someone has left the experiment by closing the browser window? If so, that could trigger a notification that the person has withdrawn. This would mean that people couldn't resume by re-opening the experiment, but I would be willing to sacrifice that feature (I rarely implement it anyways) in experiments where I cared strongly about getting a precise N in each condition.

**Comment by gureckis** [comment]
Yeah, psiTurk does that be default (records when people close browser after getting through instructions ... assuming experimenter calls psiturk.finishInstructions() in their javascript).  After a lot of discussion with the Facebook guys behind PlanOut, we have realized that the best solution for dealing with dropouts is just to plan to collect a larger N.  Adaptively "refilling" conditions that never complete can lead to sequential dependencies in assignments that can be a possible confound.
